server:
  port: 9098
  
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RishabhSinghla/microservice-tutorial-config
          clone-on-start: true
